buildaddons: &buildaddons
  apt:
    sources:
    - sourceline: deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64
        /
      key_url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
    - sourceline: deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64
        /
    - ubuntu-toolchain-r-test
    packages:
    - libopenblas-dev
    - libgsl0-dev
    - liblapacke-dev
    - google-perftools
    - libgoogle-perftools-dev
    - graphviz
    - cmake
    - libmicrohttpd-dev
    - libssl-dev
    - libpci-dev
    - libhwloc-dev
    - libnuma-dev
    - gcc-7
    - g++-7
    - libnccl2
    - cuda-cudart-dev-9-2
    - cuda-libraries-dev-9-2
    - cuda-command-line-tools-9-2
    - cuda-cublas-dev-9-2
    - libcudnn7
    - libcudnn7-dev

language: cpp
dist: trusty
sudo: true
services:
- docker
cache:
  apt: true
  directories:
  - "$HOME/.cache/cuda"
  - "$HOME/.hunter"
  - "$HOME/.cmake"
addons:
  
env:
  global:
  - CXX_COMPILER=g++-7
  - CMAKE_CXX_COMPILER=g++-7
  - CC=gcc-7
  - CXX=g++-7
  - CMAKE_C_COMPILER=gcc-7
  - CMAKE_CUDA_HOST_COMPILER=g++7
  - CMAKE_CUDA_COMPILER=/usr/local/cuda-9.2/bin/nvcc
  - CUDACXX=/usr/local/cuda-9.2/bin/nvcc
  - LD_LIBRARY_PATH=/usr/local/nvidia/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
  - LD_LIBRARY_PATH=/usr/local/cuda-9.2/nvvm/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
  - LD_LIBRARY_PATH=/usr/local/cuda-9.2/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
  - PATH=/usr/local/cuda-9.2/bin${PATH:+:${PATH}}
  - CMAKE_VERSION=3.11.1
  - CMAKE_ROOT=${HOME}/.cmake
matrix:
  include:
    - env: DO_BUILD=0 DOCKER_CUDA=75 DOCKER_ARCH=amd64
    - env: DO_BUILD=0 DOCKER_CUDA=80 DOCKER_ARCH=amd64 
    - env: DO_BUILD=0 DOCKER_CUDA=92 DOCKER_ARCH=amd64
    - env: DO_BUILD=0 DOCKER_CUDA=80 DOCKER_ARCH=ppc64le
    - env: DO_BUILD=0 DOCKER_CUDA=92 DOCKER_ARCH=ppc64le
    - env: DO_BUILD=1 USE_HUNTER=ON
      addons: *buildaddons
    - env: DO_BUILD=1 USE_HUNTER=OFF
      addons: *buildaddons
  allow_failures:
    - env: DO_BUILD=0 DOCKER_CUDA=75 DOCKER_ARCH=amd64
    - env: DO_BUILD=0 DOCKER_CUDA=80 DOCKER_ARCH=ppc64le
    - env: DO_BUILD=0 DOCKER_CUDA=92 DOCKER_ARCH=ppc64le
    - env: DO_BUILD=1 USE_HUNTER=OFF

before_install:
- cd ${TRAVIS_BUILD_DIR}
- ./ci/install_cmake.sh
- export PATH=${CMAKE_ROOT}/bin:$PATH
- sudo ln -s /usr/local/cuda-9.2 /usr/local/cuda
script:
- cd ${TRAVIS_BUILD_DIR}
- ./ci/build.sh
- cd ${TRAVIS_BUILD_DIR}
- ./ci/build_and_push_docker.sh
