
[build]
  base    = "."
  command = "echo \"x1\" && git submodule update --init --recursive ; ls -l ; ls -l example_scope;  cp example_scope/docs docs/example_scope ; cp comm_scope/docs docs/comm_scope"
  build = "echo \"x2\" &&  git submodule update --init --recursive ;  ls -l ;   ls -l example_scope; cp example_scope/docs docs/example_scope ; cp comm_scope/docs docs/comm_scope"
  publish = "docs"


