
[build]
  base    = "docs"
  command = """
cp -v ../README.md . ;
cp -rv ../scopes/example_scope/docs example_scope ;
cp -v ../scopes/example_scope/README.md example_scope ;
cp -rv ../scopes/comm_scope/docs comm_scope ;
cp -v ../scopes/comm_scope/README.md comm_scope"""
  publish = "docs"


